name: test

on: 
  push:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4.9.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build release
        run: ./gradlew build